environment:
  matrix:
    # - CMAKE_GENERATOR: "Visual Studio 12 2013"
    #   MPI_HOME: "C:/Program Files (x86)/Microsoft SDKs/MPI"
    - CMAKE_GENERATOR: "Visual Studio 14 2015"
      MPI_HOME: "C:/Program Files (x86)/Microsoft SDKs/MPI"
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #   CMAKE_GENERATOR: "Visual Studio 15 2017"
    #   MPI_HOME: "C:/Program Files (x86)/Microsoft SDKs/MPI"
install:
  - git submodule update --init --recursive
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ..
  - cmd: cmake --build . --config Release
  - cmd: bin\test_target.exe
  # - cmd: bin\benchmark_target.exe
  - cmd: bin\example_pipelines.exe ..\samples\example_pipelines\pipeline.yaml
